name: CI for Tcl on Windows

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    # Étape 1 : Vérifiez le dépôt
    - name: Checkout repository
      uses: actions/checkout@v3

    # Étape 2 : Installer Tcl
    - name: Install Tcl
      run: |
        choco install tcl -y
        tclsh --version

    # Étape 3 : Lancer les scripts/tests Tcl
    - name: Run Tcl scripts/tests
      run: |
        tclsh ./tests/your_test_script.tcl
