name: CI for Tcl on Windows using nmake

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    # Étape 1 : Vérifiez le dépôt
    - name: Checkout repository
      uses: actions/checkout@v3
          # Note msvc defaults to 64-bit

    # Étape 2 : Initialiser MSVC
    - name: Init MSVC
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64

    # Étape 3 : Télécharger les sources de Tcl
    - name: Download Tcl source
      run: |
        curl -L https://sourceforge.net/projects/tcl/files/Tcl/9.0.0/tcl900-src.zip -o tcl900-src.zip
        tar -xf tcl900-src.zip

    # Étape 4 : Compiler Tcl avec nmake
    - name: Build Tcl with nmake
      run: |
        cd tcl9.0.0\win
        nmake -f makefile.vc INSTALLDIR=C:\Tcl90
        nmake -f makefile.vc install INSTALLDIR=C:\Tcl90

    # Étape 5 : Vérifier l'installation de Tcl
    - name: Verify Tcl installation
      run: |
        C:\Tcl90\bin\tclsh.exe --version

    # Étape 6 : Lancer les scripts/tests Tcl
    - name: Run Tcl scripts/tests
      run: |
        C:\Tcl90\bin\tclsh.exe ./test/test_script.tcl
